In [1]:
import numpy as np
import dask.array as da
import pandas as pd

from backtest.data.loader import *

In [2]:
filename = "./data/기관외국인동향.db"
data = read_db_multi(filename, num_process=6)

In [6]:
data["A005930"]

<div>
<style scoped>
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>종가</th>
      <th>대비</th>
      <th>거래량(주)</th>
      <th>기관_매수량(주)</th>
      <th>기관_매도량(주)</th>
      <th>기관_순매수(주)</th>
      <th>외국인_매수량(주)</th>
      <th>외국인_매도량(주)</th>
      <th>외국인_순매수(주)</th>
    </tr>
    <tr>
      <th>날짜</th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>2002-01-02</th>
      <td>308000.0</td>
      <td>29000.0</td>
      <td>1142079.0</td>
      <td>318980.0</td>
      <td>221221.0</td>
      <td>97759.0</td>
      <td>405060.0</td>
      <td>200370.0</td>
      <td>204690.0</td>
    </tr>
    <tr>
      <th>2002-01-03</th>
      <td>302000.0</td>
      <td>-6000.0</td>
      <td>885636.0</td>
      <td>303330.0</td>
      <td>227320.0</td>
      <td>76010.0</td>
      <td>210840.0</td>
      <td>194585.0</td>
      <td>16255.0</td>
    </tr>
    <tr>
      <th>2002-01-04</th>
      <td>319000.0</td>
      <td>17000.0</td>
      <td>1009482.0</td>
      <td>282590.0</td>
      <td>302472.0</td>
      <td>-19882.0</td>
      <td>404220.0</td>
      <td>186348.0</td>
      <td>217872.0</td>
    </tr>
    <tr>
      <th>2002-01-07</th>
      <td>318000.0</td>
      <td>-1000.0</td>
      <td>1029132.0</td>
      <td>253161.0</td>
      <td>332482.0</td>
      <td>-79321.0</td>
      <td>387052.0</td>
      <td>349270.0</td>
      <td>37782.0</td>
    </tr>
    <tr>
      <th>2002-01-08</th>
      <td>311500.0</td>
      <td>-6500.0</td>
      <td>760142.0</td>
      <td>169190.0</td>
      <td>197621.0</td>
      <td>-28431.0</td>
      <td>206720.0</td>
      <td>273440.0</td>
      <td>-66720.0</td>
    </tr>
    <tr>
      <th>2002-01-09</th>
      <td>322500.0</td>
      <td>11000.0</td>
      <td>902401.0</td>
      <td>173951.0</td>
      <td>305820.0</td>
      <td>-131869.0</td>
      <td>337030.0</td>
      <td>294124.0</td>
      <td>42906.0</td>
    </tr>
    <tr>
      <th>2002-01-10</th>
      <td>308000.0</td>
      <td>-14500.0</td>
      <td>1096986.0</td>
      <td>280792.0</td>
      <td>471535.0</td>
      <td>-190743.0</td>
      <td>424150.0</td>
      <td>390445.0</td>
      <td>33705.0</td>
    </tr>
    <tr>
      <th>2002-01-11</th>
      <td>306000.0</td>
      <td>-2000.0</td>
      <td>953687.0</td>
      <td>224770.0</td>
      <td>270770.0</td>
      <td>-46000.0</td>
      <td>326520.0</td>
      <td>418790.0</td>
      <td>-92270.0</td>
    </tr>
    <tr>
      <th>2002-01-14</th>
      <td>330000.0</td>
      <td>24000.0</td>
      <td>978026.0</td>
      <td>231590.0</td>
      <td>201660.0</td>
      <td>29930.0</td>
      <td>237830.0</td>
      <td>96160.0</td>
      <td>141670.0</td>
    </tr>
    <tr>
      <th>2002-01-15</th>
      <td>312000.0</td>
      <td>-18000.0</td>
      <td>1377508.0</td>
      <td>331880.0</td>
      <td>289150.0</td>
      <td>42730.0</td>
      <td>174440.0</td>
      <td>673331.0</td>
      <td>-498891.0</td>
    </tr>
    <tr>
      <th>2002-01-16</th>
      <td>301500.0</td>
      <td>-10500.0</td>
      <td>1206614.0</td>
      <td>335530.0</td>
      <td>225170.0</td>
      <td>110360.0</td>
      <td>220148.0</td>
      <td>546866.0</td>
      <td>-326718.0</td>
    </tr>
    <tr>
      <th>2002-01-17</th>
      <td>300000.0</td>
      <td>-1500.0</td>
      <td>1112140.0</td>
      <td>357426.0</td>
      <td>97554.0</td>
      <td>259872.0</td>
      <td>206000.0</td>
      <td>583591.0</td>
      <td>-377591.0</td>
    </tr>
    <tr>
      <th>2002-01-18</th>
      <td>296000.0</td>
      <td>-4000.0</td>
      <td>885232.0</td>
      <td>260195.0</td>
      <td>276874.0</td>
      <td>-16679.0</td>
      <td>257330.0</td>
      <td>325819.0</td>
      <td>-68489.0</td>
    </tr>
    <tr>
      <th>2002-01-21</th>
      <td>291000.0</td>
      <td>-5000.0</td>
      <td>825347.0</td>
      <td>280730.0</td>
      <td>92942.0</td>
      <td>187788.0</td>
      <td>136610.0</td>
      <td>492467.0</td>
      <td>-355857.0</td>
    </tr>
    <tr>
      <th>2002-01-22</th>
      <td>300000.0</td>
      <td>9000.0</td>
      <td>657912.0</td>
      <td>148791.0</td>
      <td>150611.0</td>
      <td>-1820.0</td>
      <td>113520.0</td>
      <td>156778.0</td>
      <td>-43258.0</td>
    </tr>
    <tr>
      <th>2002-01-23</th>
      <td>308000.0</td>
      <td>8000.0</td>
      <td>798014.0</td>
      <td>234590.0</td>
      <td>134930.0</td>
      <td>99660.0</td>
      <td>192030.0</td>
      <td>287280.0</td>
      <td>-95250.0</td>
    </tr>
    <tr>
      <th>2002-01-24</th>
      <td>310000.0</td>
      <td>2000.0</td>
      <td>768310.0</td>
      <td>362607.0</td>
      <td>224343.0</td>
      <td>138264.0</td>
      <td>161310.0</td>
      <td>166060.0</td>
      <td>-4750.0</td>
    </tr>
    <tr>
      <th>2002-01-25</th>
      <td>323000.0</td>
      <td>13000.0</td>
      <td>1137546.0</td>
      <td>397509.0</td>
      <td>265220.0</td>
      <td>132289.0</td>
      <td>466410.0</td>
      <td>127390.0</td>
      <td>339020.0</td>
    </tr>
    <tr>
      <th>2002-01-28</th>
      <td>318500.0</td>
      <td>-4500.0</td>
      <td>674726.0</td>
      <td>170430.0</td>
      <td>200810.0</td>
      <td>-30380.0</td>
      <td>279300.0</td>
      <td>234767.0</td>
      <td>44533.0</td>
    </tr>
    <tr>
      <th>2002-01-29</th>
      <td>315000.0</td>
      <td>-3500.0</td>
      <td>642877.0</td>
      <td>258250.0</td>
      <td>209300.0</td>
      <td>48950.0</td>
      <td>158440.0</td>
      <td>237180.0</td>
      <td>-78740.0</td>
    </tr>
    <tr>
      <th>2002-01-30</th>
      <td>303000.0</td>
      <td>-12000.0</td>
      <td>791627.0</td>
      <td>243690.0</td>
      <td>190900.0</td>
      <td>52790.0</td>
      <td>159910.0</td>
      <td>362020.0</td>
      <td>-202110.0</td>
    </tr>
    <tr>
      <th>2002-01-31</th>
      <td>300500.0</td>
      <td>-2500.0</td>
      <td>734664.0</td>
      <td>178298.0</td>
      <td>329103.0</td>
      <td>-150805.0</td>
      <td>244200.0</td>
      <td>193650.0</td>
      <td>50550.0</td>
    </tr>
    <tr>
      <th>2002-02-01</th>
      <td>309000.0</td>
      <td>8500.0</td>
      <td>712813.0</td>
      <td>155770.0</td>
      <td>307666.0</td>
      <td>-151896.0</td>
      <td>312460.0</td>
      <td>74544.0</td>
      <td>237916.0</td>
    </tr>
    <tr>
      <th>2002-02-04</th>
      <td>312000.0</td>
      <td>3000.0</td>
      <td>476171.0</td>
      <td>103675.0</td>
      <td>199700.0</td>
      <td>-96025.0</td>
      <td>220170.0</td>
      <td>54662.0</td>
      <td>165508.0</td>
    </tr>
    <tr>
      <th>2002-02-05</th>
      <td>323000.0</td>
      <td>11000.0</td>
      <td>973561.0</td>
      <td>353882.0</td>
      <td>299560.0</td>
      <td>54322.0</td>
      <td>149670.0</td>
      <td>121080.0</td>
      <td>28590.0</td>
    </tr>
    <tr>
      <th>2002-02-06</th>
      <td>319000.0</td>
      <td>-4000.0</td>
      <td>636965.0</td>
      <td>303790.0</td>
      <td>156892.0</td>
      <td>146898.0</td>
      <td>147220.0</td>
      <td>223317.0</td>
      <td>-76097.0</td>
    </tr>
    <tr>
      <th>2002-02-07</th>
      <td>315000.0</td>
      <td>-4000.0</td>
      <td>739516.0</td>
      <td>284983.0</td>
      <td>215263.0</td>
      <td>69720.0</td>
      <td>204950.0</td>
      <td>251752.0</td>
      <td>-46802.0</td>
    </tr>
    <tr>
      <th>2002-02-08</th>
      <td>321000.0</td>
      <td>6000.0</td>
      <td>682188.0</td>
      <td>203530.0</td>
      <td>218170.0</td>
      <td>-14640.0</td>
      <td>268900.0</td>
      <td>275868.0</td>
      <td>-6968.0</td>
    </tr>
    <tr>
      <th>2002-02-14</th>
      <td>355000.0</td>
      <td>34000.0</td>
      <td>1967365.0</td>
      <td>547100.0</td>
      <td>316470.0</td>
      <td>230630.0</td>
      <td>898131.0</td>
      <td>450138.0</td>
      <td>447993.0</td>
    </tr>
    <tr>
      <th>2002-02-15</th>
      <td>341500.0</td>
      <td>-13500.0</td>
      <td>857239.0</td>
      <td>349850.0</td>
      <td>171254.0</td>
      <td>178596.0</td>
      <td>184940.0</td>
      <td>448654.0</td>
      <td>-263714.0</td>
    </tr>
    <tr>
      <th>...</th>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
    </tr>
    <tr>
      <th>2018-09-07</th>
      <td>44900.0</td>
      <td>-1200.0</td>
      <td>18285508.0</td>
      <td>6582348.0</td>
      <td>4698407.0</td>
      <td>1883941.0</td>
      <td>3580064.0</td>
      <td>11431236.0</td>
      <td>-7851172.0</td>
    </tr>
    <tr>
      <th>2018-09-10</th>
      <td>45500.0</td>
      <td>600.0</td>
      <td>9979838.0</td>
      <td>2395766.0</td>
      <td>3857335.0</td>
      <td>-1461569.0</td>
      <td>5935786.0</td>
      <td>4213739.0</td>
      <td>1722047.0</td>
    </tr>
    <tr>
      <th>2018-09-11</th>
      <td>45050.0</td>
      <td>-450.0</td>
      <td>9865790.0</td>
      <td>2687682.0</td>
      <td>2874807.0</td>
      <td>-187125.0</td>
      <td>5065707.0</td>
      <td>5340080.0</td>
      <td>-274373.0</td>
    </tr>
    <tr>
      <th>2018-09-12</th>
      <td>44550.0</td>
      <td>-500.0</td>
      <td>12995269.0</td>
      <td>4422664.0</td>
      <td>3142096.0</td>
      <td>1280568.0</td>
      <td>4732286.0</td>
      <td>8268553.0</td>
      <td>-3536267.0</td>
    </tr>
    <tr>
      <th>2018-09-13</th>
      <td>44050.0</td>
      <td>-500.0</td>
      <td>18277942.0</td>
      <td>10251961.0</td>
      <td>7378406.0</td>
      <td>2873555.0</td>
      <td>2479842.0</td>
      <td>9400575.0</td>
      <td>-6920733.0</td>
    </tr>
    <tr>
      <th>2018-09-14</th>
      <td>45850.0</td>
      <td>1800.0</td>
      <td>12446344.0</td>
      <td>3523648.0</td>
      <td>2947313.0</td>
      <td>576335.0</td>
      <td>6535936.0</td>
      <td>3871564.0</td>
      <td>2664372.0</td>
    </tr>
    <tr>
      <th>2018-09-17</th>
      <td>45150.0</td>
      <td>-700.0</td>
      <td>8123384.0</td>
      <td>1609846.0</td>
      <td>3511259.0</td>
      <td>-1901413.0</td>
      <td>3226576.0</td>
      <td>2564204.0</td>
      <td>662372.0</td>
    </tr>
    <tr>
      <th>2018-09-18</th>
      <td>45500.0</td>
      <td>350.0</td>
      <td>9987090.0</td>
      <td>2679723.0</td>
      <td>2832052.0</td>
      <td>-152329.0</td>
      <td>5862916.0</td>
      <td>4813058.0</td>
      <td>1049858.0</td>
    </tr>
    <tr>
      <th>2018-09-19</th>
      <td>46150.0</td>
      <td>650.0</td>
      <td>9367454.0</td>
      <td>2572502.0</td>
      <td>2955085.0</td>
      <td>-382583.0</td>
      <td>5655879.0</td>
      <td>3446086.0</td>
      <td>2209793.0</td>
    </tr>
    <tr>
      <th>2018-09-20</th>
      <td>47250.0</td>
      <td>1100.0</td>
      <td>13536966.0</td>
      <td>3427395.0</td>
      <td>3737426.0</td>
      <td>-310031.0</td>
      <td>8284163.0</td>
      <td>3298353.0</td>
      <td>4985810.0</td>
    </tr>
    <tr>
      <th>2018-09-21</th>
      <td>47400.0</td>
      <td>150.0</td>
      <td>14476906.0</td>
      <td>4236091.0</td>
      <td>4210180.0</td>
      <td>25911.0</td>
      <td>8033471.0</td>
      <td>7282850.0</td>
      <td>750621.0</td>
    </tr>
    <tr>
      <th>2018-09-27</th>
      <td>47500.0</td>
      <td>100.0</td>
      <td>15804586.0</td>
      <td>3639076.0</td>
      <td>4896464.0</td>
      <td>-1257388.0</td>
      <td>10390558.0</td>
      <td>8391205.0</td>
      <td>1999353.0</td>
    </tr>
    <tr>
      <th>2018-09-28</th>
      <td>46450.0</td>
      <td>-1050.0</td>
      <td>11270515.0</td>
      <td>4487415.0</td>
      <td>3567008.0</td>
      <td>920407.0</td>
      <td>4342780.0</td>
      <td>5859091.0</td>
      <td>-1516311.0</td>
    </tr>
    <tr>
      <th>2018-10-01</th>
      <td>46350.0</td>
      <td>-100.0</td>
      <td>6354983.0</td>
      <td>1937753.0</td>
      <td>2747481.0</td>
      <td>-809728.0</td>
      <td>2630307.0</td>
      <td>2221934.0</td>
      <td>408373.0</td>
    </tr>
    <tr>
      <th>2018-10-02</th>
      <td>45700.0</td>
      <td>-650.0</td>
      <td>304304.0</td>
      <td>112435.0</td>
      <td>133226.0</td>
      <td>-20792.0</td>
      <td>105134.0</td>
      <td>111423.0</td>
      <td>-6289.0</td>
    </tr>
    <tr>
      <th>2018-10-04</th>
      <td>44700.0</td>
      <td>-1000.0</td>
      <td>533018.0</td>
      <td>190649.0</td>
      <td>130517.0</td>
      <td>60132.0</td>
      <td>139930.0</td>
      <td>335386.0</td>
      <td>-195457.0</td>
    </tr>
    <tr>
      <th>2018-10-05</th>
      <td>44700.0</td>
      <td>0.0</td>
      <td>472928.0</td>
      <td>192185.0</td>
      <td>173459.0</td>
      <td>18726.0</td>
      <td>98177.0</td>
      <td>206283.0</td>
      <td>-108106.0</td>
    </tr>
    <tr>
      <th>2018-10-08</th>
      <td>44950.0</td>
      <td>250.0</td>
      <td>303660.0</td>
      <td>105115.0</td>
      <td>93527.0</td>
      <td>11588.0</td>
      <td>129929.0</td>
      <td>134058.0</td>
      <td>-4129.0</td>
    </tr>
    <tr>
      <th>2018-10-10</th>
      <td>45300.0</td>
      <td>350.0</td>
      <td>467913.0</td>
      <td>178978.0</td>
      <td>142427.0</td>
      <td>36551.0</td>
      <td>237023.0</td>
      <td>220523.0</td>
      <td>16500.0</td>
    </tr>
    <tr>
      <th>2018-10-11</th>
      <td>43100.0</td>
      <td>-2200.0</td>
      <td>844344.0</td>
      <td>350122.0</td>
      <td>256366.0</td>
      <td>93756.0</td>
      <td>176221.0</td>
      <td>446945.0</td>
      <td>-270724.0</td>
    </tr>
    <tr>
      <th>2018-10-12</th>
      <td>44000.0</td>
      <td>900.0</td>
      <td>555819.0</td>
      <td>175025.0</td>
      <td>201132.0</td>
      <td>-26107.0</td>
      <td>265377.0</td>
      <td>204469.0</td>
      <td>60908.0</td>
    </tr>
    <tr>
      <th>2018-10-15</th>
      <td>43800.0</td>
      <td>-200.0</td>
      <td>324350.0</td>
      <td>100992.0</td>
      <td>164744.0</td>
      <td>-63752.0</td>
      <td>129596.0</td>
      <td>104354.0</td>
      <td>25242.0</td>
    </tr>
    <tr>
      <th>2018-10-16</th>
      <td>43600.0</td>
      <td>-200.0</td>
      <td>298410.0</td>
      <td>101142.0</td>
      <td>131531.0</td>
      <td>-30389.0</td>
      <td>122336.0</td>
      <td>116991.0</td>
      <td>5345.0</td>
    </tr>
    <tr>
      <th>2018-10-17</th>
      <td>44150.0</td>
      <td>550.0</td>
      <td>367501.0</td>
      <td>116065.0</td>
      <td>112619.0</td>
      <td>3445.0</td>
      <td>186610.0</td>
      <td>164102.0</td>
      <td>22509.0</td>
    </tr>
    <tr>
      <th>2018-10-18</th>
      <td>44050.0</td>
      <td>-100.0</td>
      <td>368460.0</td>
      <td>103942.0</td>
      <td>164055.0</td>
      <td>-60113.0</td>
      <td>222538.0</td>
      <td>153602.0</td>
      <td>68936.0</td>
    </tr>
    <tr>
      <th>2018-10-19</th>
      <td>43900.0</td>
      <td>-150.0</td>
      <td>343941.0</td>
      <td>151823.0</td>
      <td>126463.0</td>
      <td>25361.0</td>
      <td>111966.0</td>
      <td>167957.0</td>
      <td>-55992.0</td>
    </tr>
    <tr>
      <th>2018-10-22</th>
      <td>43550.0</td>
      <td>-350.0</td>
      <td>364048.0</td>
      <td>120978.0</td>
      <td>110018.0</td>
      <td>10960.0</td>
      <td>166771.0</td>
      <td>193948.0</td>
      <td>-27177.0</td>
    </tr>
    <tr>
      <th>2018-10-23</th>
      <td>43050.0</td>
      <td>-500.0</td>
      <td>410359.0</td>
      <td>156057.0</td>
      <td>162976.0</td>
      <td>-6919.0</td>
      <td>100375.0</td>
      <td>156207.0</td>
      <td>-55832.0</td>
    </tr>
    <tr>
      <th>2018-10-24</th>
      <td>42550.0</td>
      <td>-500.0</td>
      <td>575195.0</td>
      <td>305432.0</td>
      <td>134550.0</td>
      <td>170882.0</td>
      <td>175822.0</td>
      <td>321131.0</td>
      <td>-145309.0</td>
    </tr>
    <tr>
      <th>2018-10-25</th>
      <td>41000.0</td>
      <td>-1550.0</td>
      <td>793656.0</td>
      <td>321604.0</td>
      <td>106325.0</td>
      <td>215279.0</td>
      <td>293776.0</td>
      <td>564891.0</td>
      <td>-271115.0</td>
    </tr>
  </tbody>
</table>
<p>4155 rows × 9 columns</p>
</div>